sudo: required
services: 
  - docker

before_install:
  - docker build -t mikeonline/docker-react -f Dockerfile.dev .

script:
  - docker run mikeonline/docker-react npm run test -- --watchAll=false 

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-144056098056"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY